apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue-project-ingress
  namespace: skala-practice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: vue.skala.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue-project-service
                port:
                  number: 80
